version: '3'

services:
  google-cloud-pubsub:
    build:
      dockerfile: Dockerfile
      context: ../../
    env_file:
      - ../../.env
    volumes:
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/var/.credentials/key.json
      - /resources/data:/app/resources/data
      - virtualenvs:/root/.local/share/virtualenvs
