apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: google-cloud-pubsub-service-account
                  key: GCP_CREDENTIALS_kEY
            - name: MAX_BYTES_PER_BATCH
              value: '{{ .Values.environment.maxByesPerBatch }}'
            - name: MAX_MESSAGES_PER_BATCH
              value: '{{ .Values.environment.maxMessagesPerBatch }}'
            - name: MAX_LATENCY_TO_PUBLISH
              value: '{{ .Values.environment.maxLatencyToPublish }}'
            - name: TOPIC_NAME
              value: '{{ .Values.environment.topicName }}'
            - name: TOPIC_PROJECT_ID
              value: '{{ .Values.environment.topicProject }}'
            - name: TOTAL_REPLICATION
              value: '{{ .Values.environment.totalReplication }}'
          resources:
            limits:
              cpu: {{.Values.limits.cpu}}
              memory: {{.Values.limits.memory}}
            requests:
              cpu: {{.Values.requests.cpu}}
              memory: {{.Values.requests.memory}}
